.only-default: &only-default
  only:
    - api
    - web
    - master

stages:
  - install
  # - test
  - build
  - deploy

install:
  <<: *only-default
  stage: install
  image: node
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  script:
    - echo "Install project dependecies"
    - npm install
    - echo "Install successful"

# test:
#   <<: *only-default
#   stage: test
#   image: node
#   script:
#     - echo "Testing App"
#     - npm test
#     - echo "Test successful"
#   coverage: /All\sfiles.*?\s+(\d+.\d+)/

build:
  <<: *only-default
  stage: build
  image: node
  script:
    - echo "Build started"
    - REACT_APP_API_KEY=$REACT_APP_API_KEY REACT_APP_API_KEY_HASH=$REACT_APP_API_KEY_HASH REACT_APP_ENVIRONMENT=prod npm run build
    - echo "Build successfull"
  artifacts:
    paths:
      - build/

deploy:
  <<: *only-default
  stage: deploy
  dependencies:
    - build
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws s3 cp build/ s3://$S3_BUCKET/ --recursive
